### ISSUE TITLE
[ticketer] Closed channel permission

### ISSUE THREAD

**Issue by dducted** [Dav-Git/Dav-Cogs#32]
Hi there,

I thought it might be a great option if the channel for the ticket opener remains visible after closure, user just cant text in it anymore. So the user has a reference at a later time and the channel doesnt just fully disappear. Great cog though, liking it a lot!

**Comment by Dav-Git** [comment]
Thank you very much for the feedback. I personally think closed tickets are more of an archive for staff and am actually going to send the management embeds into said channels at the end. Since these management embeds continue staff only notes I wouldn't want the ticket opener to be able to read these messages. If you want to do this on your server however you can use manual permission overwrites (channel settings) to allow them to see into closed tickets.
